language: c

os:
    - linux
    - osx

env:
    - PT_PHP_VERSION=7.1.2
    - PT_PHP_VERSION=7.0.16
    - PT_PHP_VERSION=5.6.30
    - PT_PHP_VERSION=5.5.38
    - PT_PHP_VERSION=5.4.37
    - PT_PHP_VERSION=5.3.29
    - PT_PHP_VERSION=5.2.17

matrix:
    exclude:
        - os: osx
          env: PT_PHP_VERSION=5.2.17
        - os: osx
          env: PT_PHP_VERSION=5.3.29

script:
  - cc --version
